#!/usr/bin/env bash
#check command-line parameters

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

#assign arguments to vars

file_path=$f
ip=$i
username=$u
ssh_key_path=$s

#disable strict host key checking

scp -o "StrictHostKeyChecking=no" -i "$ssh_key_path" "$file_path" "$username@$ip:~/"


#checking if file transfer success?

if [ $? -eq 0 ]
then
	echo "File Transfer Success"
else
	echo "File Transfer Failed"
fi
