#!/usr/bin/env bash

#update packages
sudo apt-get update
sudo apt-get -y install nginx

#Configuring the Uncomplicated Firewall (UFW) to allow incoming traffic for the Nginx HTTP service
sudo ufw allow 'Nginx HTTP'

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing Nginx configurations for Syntax errors
sudo nginx -t

#start nginx
sudo systemctl restart nginx
