#!/usr/bin/env bash
#Script that configures nignx server to perform a 301-redirection to another page.

#update packages&&install nginx
sudo apt-get update
sudo apt-get install -y nginx

#this is my index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

#301 Redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/sherdooh permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#restart nginx
sudo systemctl restart nginx

