#!/usr/bin/env bash
# This script installs and configures a load balancer
# Enables haproxy
sudo apt-get -y install haproxy
sudo chown $USER:$USER /etc/haproxy/haproxy.cfg
sudo chown $USER:$USER /etc/default/haproxy

server_config=\
"
frontend samson_front_end
        bind *:80
        mode http
	default_backend samson_back_end
backend samson_back_end
        balance roundrobin
        mode http
        server 945-web-01 54.197.206.200 check
        server 945-web-02 54.162.98.103 check
"
sudo echo "$server_config" >> /etc/haproxy/haproxy.cfg

sudo echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy restart
