#!/bin/bash

apt update
apt install nginx -y

if ! service nginx status | grep -q "active (running)"; then
    service nginx start
fi

if ! netstat -tuln | grep -q ":80"; then
    sed -i 's/listen\s*\(.*\)/listen 80;/g' /etc/nginx/nginx.conf
    service nginx restart
fi

