#!/usr/bin/env bash
#Configures Nginx to listen on port 80.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

#restart nginx
sudo systemctl restart nginx

